forums/urls.py
from django.conf.urls import patterns, include, url
from .views import ForumView, ThreadView, SinglePostView, ReplyFormView, CreateThreadView 

urlpatterns = patterns('',

    url(r'^forum/(?P<pk>\d+)/$', ForumView.as_view(), name='single_forum'),
    url(r'^thread/(?P<pk>\d+)/$', ThreadView.as_view(), name='thread'),
    url(r'^thread/reply/(?P<pk>\d+)/$', ReplyFormView.as_view(), name='reply'),
    url(r'^single_post/(?P<pk>\d+)/$', SinglePostView.as_view(), name='single_post'),
    url(r'^forum/new_thread/(?P<pk>\d+)/$', CreateThreadView.as_view(), name='create_thread'),
    url(r'^quote/(?P<pk>\d+)/$', 'forums.views.quote', name='quote'),
)

pizza/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from forums.views import ForumIndexView
from profiles.views import RegisterView, LoginView

urlpatterns = patterns('',

    url(r'^$', ForumIndexView.as_view(), name='main'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', 'profiles.views.my_logout', name='logout'),
    url(r'^forums/', include('forums.urls', namespace='forums')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^message/', include('directmessages.urls', namespace='directmessages')),
    url(r'^search/', 'forums.views.search', name='search'),
    url(r'^admin/', include(admin.site.urls)),
    
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.conf.urls import patterns, include, url

from profiles.views import ProfileView, ProfileIndexView

urlpatterns = patterns('',

    url(r'^(?P<slug>[-\w]+)/$', ProfileView.as_view(), name='profile'),
    url(r'^$', ProfileIndexView.as_view(), name='profile_index'),
    url(r'^banned/banned/$', 'profiles.views.banned', name='banned'),
)

forums/models.py
from django.db import models


from django.core.paginator import Paginator

from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


from precise_bbcode.fields import BBCodeTextField


class ForumCategory(models.Model):
    title = models.CharField(max_length=100)
    
    
    def __unicode__(self):
        return self.title





class Forum(models.Model):
    title = models.CharField(max_length=100)
    #moderators = models.ManyToManyField(User, blank=True, null=True)
    
    category = models.ForeignKey(ForumCategory)
    is_active = models.BooleanField(default=True)
    custom_css = models.FileField(upload_to='forum_stylesheets/%Y/%m/%d/', blank=True, null=True)
    
    def get_last_post(self):
        return self.thread_set.all().latest('last_post').post_set.all().latest('created')
    
    def get_absolute_url(self):
        return reverse('forums:single_forum', args=[self.id])

    
    def get_most_popular_thread(self):
        counter = {}
        max_count = 0
        for thread in self.thread_set.all():
            counter[thread.id] = thread.count_all_posts()
            if counter[thread.id] > max_count:
                max_count = counter[thread.id]
                favorite = thread.id
        if max_count == 0:
            favorite = None
        return Thread.objects.get(id=favorite)
    
    def get_most_popular_thread_url(self):
        favorite = self.get_most_popular_thread().id
        return Thread.objects.get(id=favorite).get_absolute_url()
    
    
    def get_num_posts(self):
        postcount = []
        for thread in self.thread_set.all():
            postcount.append(thread.count_all_posts())
        return sum(postcount)
    
    
    
    
    
    def __unicode__(self):
        return self.title


class Thread(models.Model):
    title = models.CharField(max_length=100)
    forum = models.ForeignKey(Forum)
    creator = models.ForeignKey(User)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    last_post = models.DateTimeField(auto_now_add=False, auto_now=True)

    
    class Meta:
        ordering = ['-last_post']
    
    
    def get_last_post(self):
        return self.post_set.all().latest('created')

    def num_replies(self, ):
        return self.post_set.all().count() - 1

    def count_all_posts(self):
        return self.post_set.all().count()
    
    def get_absolute_url(self):
        return reverse('forums:thread', args=[self.id])
    
    def get_last_30_posts(self):
        return self.post_set.all()[0:30]

    

    
    
    def __unicode__(self):
        return self.title



    
class Post(models.Model):
    thread = models.ForeignKey(Thread)
    author = models.ForeignKey(User)
    text = BBCodeTextField()
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    edited = models.DateTimeField(auto_now_add=False, auto_now=True)
    
    class Meta:
        ordering = ['created']
    
    def get_absolute_url(self):
        return reverse('forums:single_post', args=[self.id])
    
    #for this redirect to work properly, the pagination number argument
    #in this function must match the paginate_by value in ThreadView.
        
    def link_to_post_in_thread(self):
        thread_posts = Post.objects.filter(thread_id=self.thread.id)
        paginator = Paginator(thread_posts, 10)
        target_page = None
        for page_number in range(1, paginator.num_pages+1):
            if self in paginator.page(page_number).object_list:
                target_page = page_number
                break
            else:
                pass
        if target_page != None:
            return '/forums/thread/%d/?page=%d' %(self.thread.id, target_page)
    
    
    
    def __unicode__(self):
        return str(self.author)

forums/forms.py
from django import forms
from django.forms import Textarea, ModelForm
from forums.models import Thread, Post

EMPTY_ITEM_ERROR = 'SAY SOMETHING DINGUS!'
BANNED_USER_ERROR = 'SHUT IT DINGUS!'

class PostForm(forms.ModelForm):
    title = forms.CharField(required=False, widget=forms.HiddenInput())
    class Meta:
        model = Post
        fields = ['title','text']
        widgets = {
            'text': forms.Textarea(attrs={
                #'cols':40,
                'placeholder': 'Start typing to make a post...',
                'style':'resize:none',
            })}


        

  



class NewThreadForm(PostForm):
    title = forms.CharField(
        max_length=100, required=True,
        error_messages={'required': EMPTY_ITEM_ERROR},
        widget=forms.TextInput(attrs={'placeholder':'Put your title here...'}))

forums/views.py
from django.contrib import messages
from django.contrib.auth.models import User

from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import Http404, HttpResponse
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.list import MultipleObjectMixin

from .models import Forum, Thread, Post, ForumCategory
from .forms import PostForm, NewThreadForm

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from profiles.custom import active_and_login_required

import json
from itertools import chain


'''
rewrite tests for this first view
'''




class ForumIndexView(ListView):
    template_name = 'index.html'
    model = ForumCategory
    

    
class ForumView(SingleObjectMixin, ListView):
    template_name = 'forum.html'
    model = Thread
    paginate_by = 30
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Forum.objects.filter(id=kwargs.get('pk', None)))
        return super(ForumView, self).get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super(ForumView, self).get_context_data(**kwargs)
        context['forum'] = self.object
        return context
        
    def get_queryset(self):
        return self.object.thread_set.all()
    



class ThreadView(SingleObjectMixin, ListView):
    template_name = 'thread.html'
    model = Post
    paginate_by = 10
    
    def get(self, request, *args, **kwargs):
        print request.GET
        self.object = self.get_object(queryset=Thread.objects.filter(id=kwargs.get('pk', None)))
        request.session['thread'] = self.object.id
        print 'thread id sent to session %s' % request.session['thread']
        return super(ThreadView, self).get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super(ThreadView, self).get_context_data(**kwargs)
        context['thread'] = self.object
        context['form'] = PostForm
        return context
    
    def get_queryset(self):
        return self.object.post_set.all()



#rewrite these tests.

class ReplyFormView(FormView):
    form_class = PostForm
    template_name = 'thread.html'
    
    
    
    @method_decorator(active_and_login_required)
    def dispatch(self, *args, **kwargs):
        self.thread = Thread.objects.get(id=kwargs.get('pk', None))
        return super(ReplyFormView, self).dispatch(*args, **kwargs)
    
    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = User.objects.get(id=self.request.user.id)
        post.thread = self.thread
        post.text = form.cleaned_data['text']
        post.save()
        post.thread.save()
        
        self.success_url = '/forums/thread/%d/?page=last' % self.thread.id
        return super(ReplyFormView, self).form_valid(form)


    def form_invalid(self, form):
        return HttpResponseRedirect('/forums/thread/%d/?page=last' % self.thread.id)




class SinglePostView(UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'single_post.html'


class CreateThreadView(CreateView):
    form_class = NewThreadForm
    template_name = 'new_thread.html'
    
    @method_decorator(active_and_login_required)
    def dispatch(self, *args, **kwargs):
        self.forum = Forum.objects.get(id=kwargs.get('pk', None))
        return super(CreateThreadView, self).dispatch(*args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super(CreateView, self).get_context_data(**kwargs)
        context['forum'] = self.forum
        return context    
    
    
    
    def form_valid(self, form):
        post = form.save(commit=False)
        user = self.request.user
        
        thread = Thread(
            forum_id=self.forum.id,
            creator=user,
            title=form.cleaned_data['title']
        )
        post.author = user
        post.text = form.cleaned_data['text']
        thread.save()
        post.thread = thread
        
        post.save()
        
        
        self.success_url = reverse('forums:thread', args=[thread.id])
        return super(CreateThreadView, self).form_valid(form)


    
def quote(request, pk):
    if request.method == 'GET':
        post = Post.objects.get(id=pk)
        text = str(post.text)
        author = str(post.author)
        data = json.dumps({
            'text':text,
            'author': author,
        })

        return HttpResponse(data, content_type='application/json')


def search(request):
    try:
        q = request.GET.get('q', '')
    except:
        q = False
        
    user_queryset = User.objects.filter(
        Q(username__icontains=q)
    )
    thread_queryset = Thread.objects.filter(
        Q(title__icontains=q)
    )
    post_queryset = Post.objects.filter(
        Q(text__icontains=q)
    )
    results = list(chain(user_queryset, thread_queryset, post_queryset))
                   
    if q:
        query = 'Your search for %s returned the following results:' % q
    else:
        query = None
        
    template = 'search.html'
    context = {
        'q':q,
        'query': query,
        'results': results,
    }
    return render(request, template, context)

forums/templates/base.html
{% load staticfiles %}
{% load bbcode_tags %}
<!DOCTYPE html>
<html lang='en'>
    
<head>
    

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/base.css" rel="stylesheet" media="screen">

    
    {% block title %}
{% endblock %}
{% block stylesheet %}
{% endblock %}
<style>
    {% block styles %}
{% endblock %}
   </style> 
</head>    
<body style='background-color: #E6E6E6'>
    



<div id="custom-bootstrap-menu" class="navbar navbar-default fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header"><a class="navbar-brand" href="#">It's Pizza Time!</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse navbar-menubuilder">
            <ul class="nav navbar-nav navbar-left">
                <li><a href="{% url 'main' %}">Home</a>
                </li>
                <li><a href='#' id='bbcode'>BBcode Tips</a></li>
                </li>
                <li><form class="navbar-form navbar-left" role="search" action='{% url "search" %}'>
                        <div class="form-group">
                        <input type="text" name='q' class="form-control" placeholder="Search" style='width:200px'>
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form></a>
                </li>

            </ul>

      <ul class="nav navbar-nav navbar-right" role='navigation'>
            <li><a href='{% url "profiles:profile_index" %}'>All Profiles</a></li>
            {% if request.user.is_authenticated == True %}
                <li><a href="{% url 'profiles:profile' request.user.profile.slug %}">My Profile</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            
        {% else %}
            
            <li><a href="{% url 'login' %}">Log In</a></li>
            <li><a href="{% url 'register' %}">Register</a></li>
        {% endif %}
          </ul>


        </div>
    </div>
</div>
<div id='dialog-bbcode' title='How to use BBCode in the forums and in private messages'>
    <p style='color:black'>This forum uses Django-Precise-BBCode.
    You can find the documentation
    <a href='http://django-precise-bbcode.readthedocs.org/en/1.0.8/index.html'>here</a>.</p>
    <table class='table' style='overflow: scroll; height: 500px;'>
        
        <thead>
            
            <th>BBCode</th>
            <th>Function</th>
            <th>Options</th>
            <th>Examples</th>
        </thead>
        <tbody>
            <tr>
                <td>B</td>
                <td>creates bold text</td>
                <td></td>
                <td>[b]bold text[/b]</td>
            </tr>
            <tr>
                <td>i</td>
                <td>creates italic text</td>
                <td></td>
                <td>[i]italics text[/i]</td>
            </tr>
            <tr>
                <td>u</td>
                <td>creates underlined text</td>
                <td></td>
                <td>[u]underlined text[/u]</td>
            </tr>
            <tr>
                <td>s</td>
                <td>strikes through text</td>
                <td></td>
                <td>[s]strike text[/s]</td>
            </tr>
            <tr>
                <td>list</td>
                <td>creates an unordered list</td>
                <td>1: ordered list, A: ordered list (alphabetic)</td>
                <td>[list][*]one[*]two[/list], [list=1][*]one[*]two[/list]</td>
            </tr>
            <tr>
                <td>*</td>
                <td>creates a list item</td>
                <td></td>
                <td>[list][*]one[*]two[/list]</td>
            </tr>
            <tr>
                <td>code</td>
                <td>retains all formatting</td>
                <td></td>
                <td>[code][b]example[/b][/code]</td>
            </tr>
            <tr>
                <td>quote</td>
                <td>creates a blockquote</td>
                <td></td>
                <td>[quote]quoted string[/quote]</td>
            </tr>            
            <tr>
                <td>center</td>
                <td>creates a centered block</td>
                <td></td>
                <td>[center]example[/center]</td>
            </tr>
            <tr>
                <td>color</td>
                <td>changes text color</td>
                <td></td>
                <td>[color=red]red text[/color], [color=#FFFFFF]white text[/color]</td>
            </tr>
            <tr>
                <td>url</td>
                <td>makes a url</td>
                <td></td>
                <td>[url]http://example.com[/url]</td>
            </tr>
            <tr>
                <td>img</td>
                <td>makes an image</td>
                <td></td>
                <td>[img]http://xyz.com/logo.png[/img]</td>
            </tr>        
            
            
            
            
            
        </tbody>
        
        
        
        
        
    </table>
</div>
<div class='container'>
    
{% block breadcrumb %}
    
{% endblock %}


{% block content %}

{% endblock %}

{% block paginator %}
{% endblock %}

<div class='container'>

{% block footer %}

{% endblock %}


</div>



<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/start/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.js"></script>
 
<script>
    $(document).ready(function(){
        $(function(){
            $('#dialog-bbcode').dialog({
                autoOpen: false,
                modal:true,
                width:1000,
                height:500,
                show: {
                    effect: 'blind',
                    duration:200
                },
                hide: {
                    effect: 'explode',
                    duration: 200
                },
            });
            $('#bbcode').click(function(){
                $('#dialog-bbcode').dialog('open');
                
            });
        });
        
        
        
        
        {% block jquery %}
        {% endblock %}
    });
    
    
    
</script>
</body>    
    
    
    
    
    
</html>
    

forums/templates/footer.html
<p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; MJP &middot; <a href="#"></a> &middot; <a href="#"></a></p>

forums/templates/forum.html
{% extends 'base.html'%}

{% block title %}
    <title>{{ forum.title }}</title>
{% endblock %}

{% block stylesheet %}

{% if forum.custom_css %}
  <link rel='stylesheet' href='{{MEDIA_URL}}{{forum.custom_css}}'>
{% else %}
{% endif %}
  
{% endblock %}


{% block content %}


<div class="panel panel-general">

  <div class="panel-heading">{{ forum.title }}</div>


  <table class="table table-bordered-general">
    <thead>
        <tr><th class='col-sm-5'>Title</th><th class='col-sm-2 '>Original Poster</th>
            <th class='col-sm-2'>Replies</th><th class='col-sm-3'>Last Poster</th></tr>
        
    </thead>
    <tbody>
      <tr style='border-collapse: collapse'></tr>
        {% for thread in object_list %}
            <tr><td><a href='{{thread.get_absolute_url }}'>{{ thread.title }}</a></td><td>{{ thread.creator }}</td>
            <td>{{ thread.num_replies }}</td><td>{{ thread.last_post }}</td> </tr>
        {% endfor %}
      
        <tr style='border-bottom-width: 0'>
        <td style='border-bottom-width: 0; border-left-width: 0; border-right-width: 0;'></td>
        <td style='border-bottom-width: 0; border-left-width: 0; border-right-width: 0;'></td>
        <td style='border-bottom-width: 0; border-left-width: 0; border-right-width: 0;'></td>
        <td style='border-bottom-width: 0; border-left-width: 0; border-right-width: 0;'>
          <a href='{% url "forums:create_thread" forum.pk %}' class='btn btn-quote'>Make a Thread</a></td>
      </tr>
        
    </tbody>
    

  </table>
   
    
    
{% endblock %}

{% block paginator %}
  
  {% if is_paginated %}
  
  <div class='pagination pull-right'>
    
    <span class='page-links'>
      
      {% if page_obj.has_previous %}
        
        <a href='?page=1'>First Page</a>
        
        <a href='?page={{ page_obj.previous_page_number }}'>Previous</a>
        
      {% endif %}
      
      <span class='page-current'>
        
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}  
      </span>       
        {% if page_obj.has_next %}  
          <a href='?page={{ page_obj.next_page_number }}'>Next Page</a>  
        {% endif %}
          <a href='?page={{ page_obj.paginator.num_pages }}'>Final Page</a>

    </span> 
  </div>
{% endif %}

</div>

<br><br>
{% endblock %}


{% block footer %}
    
    {% include 'footer.html'%}
    
{% endblock %}

forums/templates/index.html
{% extends 'base.html' %}


{% block title %}

<title>Forums Index</title>

{% endblock %}

{% block stylesheet%}
    <link rel='stylesheet' href='{{STATIC_URL}}index.css'>
{% endblock %}

{% block styles %}


    
{% endblock %}


{% block content %}
    
{% for category in object_list %}
<div class="{% cycle 'panel panel-general' 'panel panel-entertainment' 'panel panel-work' %}">

  <div class="panel-heading">{{ category.title }}</div>


  <table class="table">
    <thead>
        <tr><th class='col-sm-6'>Title</th><th class='col-sm-2'>Most Popular Thread</th>
            <th class='col-sm-1'>Posts</th><th class='col-sm-2'>Most Recent Thread</th></tr>
        
    </thead>
    <tbody>
        {% for forum in category.forum_set.all %}
            <tr>
                <td><a href='{{ forum.get_absolute_url }}'>{{ forum.title}}</a></td>
                <td><a href='{{forum.get_most_popular_thread_url }}'>
                {{ forum.get_most_popular_thread }}</a></td>
                <td>{{ forum.get_num_posts }}</td>
            
            
            <td><a href='{{ forum.get_last_post.link_to_post_in_thread }}'>{{ forum.get_last_post.thread}}</a></td></tr>
        {% endfor %}
    </tbody>
  </table>
</div>


{% endfor %}



    
{% endblock %}

{% block footer %}
    
    {% include 'footer.html'%}
    
{% endblock %}

forums/templates/new_thread.html
{% extends 'base.html'%}


{% block title %}
    <title>{{ forum.title }} - New Thread</title>
{% endblock %}

{% block stylesheet %}
{% if forum.custom_css %}
  <link rel='stylesheet' href='{{MEDIA_URL}}{{forum.custom_css}}'>
{% else %}
  {% endif %}
{% endblock %}



{% block content %}
{{ forum }}

<div class="panel panel-general">

  <div class="panel-heading text-center">Make a new thread!</div>


  <table class="table table-bordered-general">

    <tbody>

        <tr><td class='col-sm-2'>{% if request.user.is_authenticated == True %}
          <p><a href='{{ request.user.profile.get_absolute_url }}'>{{request.user}}</p>
                  <img src='{{MEDIA_URL}}{{ request.user.profile.avatar }}' class='img-responsive'>
                  {% else %}
                  {% endif %}</td>
            <td>
                <form method='POST' action=''>{% csrf_token %}
                {{ form.as_p }}
                <input type='submit' value='Submit' class='btn btn-reply' style='margin-left: 400px'/>
                </form>    
            </td>
        </tr>
    </tbody>
  </table>
</div>    
    
    
{% endblock %}

{% block footer %}
    <br><br><br><br><br><br><br><br><br><br><br>
    {% include 'footer.html'%}
    
{% endblock %}

forums/templates/search.html
{% extends 'base.html'%}
{% load search_filters %}


{% block content %}



<h3>{{ query }}</h3>

<h1><u>Users</u></h1>
<ol>
    {% for item in results %}
        {% if item|classname == 'User' %}
            
            <li>
                <a href='{{ item.get_absolute_url }}'>{{ item }}</a>
                
                
            </li>
        {% endif %}
    {% endfor %}
    
</ol>

<h1><u>Threads</u></h1>

<ol>
    {% for item in results %}
        {% if item|classname == 'Thread' %}
            
            <li>
                <a href='{{ item.get_absolute_url }}'>{{ item.title }}</a>
                
                
            </li>
        {% endif %}
    {% endfor %}
    
</ol>

<h1><u>Posts</u></h1>

<ol>
    {% for item in results %}
        {% if item|classname == 'Post' %}
            
            <li>
                <a href='{{ item.get_absolute_url }}'>{{ item.text|truncatewords:50 }}</a>
                
                
            </li>
        {% endif %}
    {% endfor %}
    
</ol>





<br>
<br>
<br>




    
{% endblock %}

{% block footer %}
    
    {% include 'footer.html'%}
    
{% endblock %}

forums/templates/thread.html
{% extends 'base.html'%}


{% block title %}
    <title>{{ thread.forum.title }}</title>
{% endblock %}

{% block stylesheet %}
{% if thread.forum.custom_css %}
  <link rel='stylesheet' href='{{MEDIA_URL}}{{thread.forum.custom_css}}'>
{% else %}
{% endif %}  
{% endblock %}


{% block content %}


<div class="panel panel-general">

  <div class="panel-heading"><a href='{{ thread.forum.get_absolute_url }}'>
  {{thread.forum.title}}</a> >> <a href='{{ thread.get_absolute_url}}'>{{ thread.title }}</a></div>


  <table class="table table-bordered-general">
    <thead>
        <tr><th class='col-sm-2'>Poster</th><th class='col-sm-10'>Post</th></tr>
        
    </thead>
    <tbody>
        {% for post in object_list %}
            <tr class='post'><td><p><a href='{{ post.author.profile.get_absolute_url }}'>{{post.author}}</p>
            {% if post.author.profile.avatar %}
            
            <img src='{{MEDIA_URL}}{{post.author.profile.avatar}}' class='img-responsive'/></td>
            {% else %}
              <img src="http://media.giphy.com/media/kHIJtQ981gP1C/200_s.gif" class='img-responsive'alt="..."></td>
            {% endif %}
              <td><p>{{ post.text.rendered|safe }}</p></td></tr>
            <tr class='note'><td>{{post.created}}</td>
              <td><div class='btn-group pull-right' role='group' aria-label='...'>
                
                <a href='#' data-id='{{post.id}}' class='btn btn-quote quoter'>Quote</a>
                
             
                
              </div></td></tr>
            
        {% endfor %}
        <tr class='post'><td></td>
            <td>
                <form id='reply' method='POST' action='{% url "forums:reply" thread.pk %}'>{% csrf_token %}
                {{ form.as_p }}
                <input type='submit' value='Reply' class='btn btn-reply' style='margin-left: 400px'/>
                </form>    
            </td>
        </tr>
        

    </tbody>
  </table>
    



{% endblock %}

{% block paginator %}
  
  {% if is_paginated %}
  
  <div class='pagination pull-right'>
    
    <span class='page-links'>
      
      {% if page_obj.has_previous %}
        
        <a href='?page=1'>First Page</a>
        
        <a href='?page={{ page_obj.previous_page_number }}'>Previous</a>
        
      {% endif %}
      
      <span class='page-current'>
        
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}  
      </span>       
        {% if page_obj.has_next %}  
          <a href='?page={{ page_obj.next_page_number }}'>Next Page</a>  
        {% endif %}
          <a href='?page={{ page_obj.paginator.num_pages }}'>Final Page</a>

    </span> 
  </div>
{% endif %}

</div>
{% endblock %}    

{% block footer %}
  
  {% include 'footer.html' %}
  
{% endblock %}



{% block jquery %}

$('.quoter').click(function(){
    var postid = $(this).attr("data-id");
    var go_to_url = ('/forums/quote/x/')
    go_to_url = go_to_url.replace('x', postid);
      $.ajax({
      type:'GET',
      url: go_to_url,
      success: function(data){
      var author = (data.author)
      var text = (data.text)
      var box = $('textarea').val();
      if (box.length>0)
        $('textarea').val(box + ' ' + author + ' ' + 'said:' + ' ' + '[quote]' + text + '[/quote]');
      else
        $('textarea').val(author + ' ' + 'said:' + ' ' + '[quote]' + text + '[/quote]');
     }
     })
});  




{% endblock %}