directmessages/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',

    url(r'^compose/(?P<pk>\d+)/$', 'directmessages.views.compose', name='compose'),
    url(r'^inbox/(?P<slug>[-\w]+)/$', 'directmessages.views.inbox', name='inbox'),
    url(r'^outbox/(?P<slug>[-\w]+)/$', 'directmessages.views.outbox', name='outbox'),
    url(r'^conversation/(?P<pk>\d+)/$', 'directmessages.views.view_conversation', name='conversation'),
    url(r'^quote/(?P<pk>\d+)/$', 'directmessages.views.quote', name='quote'),

)

pizza/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from forums.views import ForumIndexView
from profiles.views import RegisterView, LoginView

urlpatterns = patterns('',

    url(r'^$', ForumIndexView.as_view(), name='main'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', 'profiles.views.my_logout', name='logout'),
    url(r'^forums/', include('forums.urls', namespace='forums')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^message/', include('directmessages.urls', namespace='directmessages')),
    url(r'^search/', 'forums.views.search', name='search'),
    url(r'^admin/', include(admin.site.urls)),
    
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.conf.urls import patterns, include, url

from profiles.views import ProfileView, ProfileIndexView

urlpatterns = patterns('',

    url(r'^(?P<slug>[-\w]+)/$', ProfileView.as_view(), name='profile'),
    url(r'^$', ProfileIndexView.as_view(), name='profile_index'),
    url(r'^banned/banned/$', 'profiles.views.banned', name='banned'),
)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from PIL import Image

from directmessages.models import DirectMessage, MessageChain


class Profile(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=25, blank=True, null=True)
    avatar = models.ImageField(upload_to='avatars/%Y/%m/%d/', blank=True, null=True)
    description = models.TextField(max_length=500, default=None, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    slug = models.SlugField(unique=True)
    
    
    def get_absolute_url(self):
        return reverse('profiles:profile', args=[self.slug])

    
    def get_num_posts(self):
        return self.user.post_set.all().count()
    def get_last_five_posts(self):
        return self.user.post_set.all().order_by('-id')[0:5]

#test these two querysets

    def get_favorite_thread(self):
        counter = {}
        max_count = 0
        for post in self.user.post_set.all():
             try:
                 counter[post.thread]
                 counter[post.thread] += 1
             except KeyError:
                 counter[post.thread] = 1
             if counter[post.thread] > max_count:
                 max_count = counter[post.thread]
                 favorite = post.thread
        if max_count == 0:
            favorite = None
        return favorite
    
    def get_favorite_forum(self):
        counter = {}
        max_count = 0
        for post in self.user.post_set.all():
            try:
                counter[post.thread.forum]
                counter[post.thread.forum] += 1
            except KeyError:
                counter[post.thread.forum] = 1
            if counter[post.thread.forum] > max_count:
                max_count = counter[post.thread.forum]
                favorite = post.thread.forum
        if max_count == 0:
            favorite = None
            
        return favorite

##trivial? maybe not test these    

    def get_all_profiles(self):
        return User.objects.all().order_by('username')
    
    def get_sent_messages(self):
        return DirectMessage.objects.filter(sender=self.user)
    
    def get_received_messages(self):
        return DirectMessage.objects.filter(recipient=self.user)
    
    class Meta:
        ordering = ['name']
    
    def __unicode__(self):
        return '%s' % self.user.username
    

    

profiles/forms.py
from django import forms
from profiles.models import Profile
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm



class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user', 'slug', 'is_active', 'name']
    

class LoginForm(AuthenticationForm):
    pass
    

class RegisterForm(UserCreationForm):

    
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        
        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

profiles/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.shortcuts import render, HttpResponseRedirect
from django.utils.text import slugify    

from django.views.generic.edit import UpdateView
from django.views.generic import FormView, ListView

from .models import Profile
from .forms import EditProfileForm, RegisterForm, LoginForm



class ProfileView(UpdateView):
    model = Profile
    template_name = 'profile.html'
    form_class = EditProfileForm

class ProfileIndexView(ListView):
    template_name = 'profile_index.html'
    model = Profile
    paginate_by = 20
    

def banned(request):
    template = 'banned.html'
    admins = User.objects.filter(is_staff=True)
    
    context = {
        'admins': admins,
    }
    return render(request, template, context)



def my_logout(request):
    logout(request)
    return HttpResponseRedirect('/')





class RegisterView(FormView):
    template_name = 'register.html'
    form_class = RegisterForm
    

    def form_valid(self, form):
        form.save()
        username = self.request.POST['username']
        password = self.request.POST['password1']
        slug = slugify(self.request.POST['username'])

        user = authenticate(username=username, password=password)
        profile = Profile.objects.create(
            user=user,slug=slug, name=username,
        )
        login(self.request, user)
        
        self.success_url = reverse('profiles:profile', args=[slug])
        return super(RegisterView, self).form_valid(form)




class LoginView(FormView):
    template_name = 'login.html'
    form_class = LoginForm

    def form_valid(self, form):
        username = self.request.POST['username']
        password = self.request.POST['password']
        user = authenticate(username=username, password=password)
        login(self.request, user)
        if self.request.user.profile.is_active == False:
            self.success_url = reverse('profiles:banned')
        else:
            try:
                self.request.session['thread']
                thread_id = self.request.session['thread']
                self.success_url ='/forums/thread/%d/?page=last' % thread_id
                
            except:
                self.success_url = reverse('profiles:profile', args=[username])
        return super(LoginView, self).form_valid(form)

profiles/templates/banned.html
{% extends 'base.html' %}



{% block content %}
    

<div class='col-sm-4 col-sm-offset-4'>   
    
<p>It looks like you've been banned! You can still access your profile.
Message an admin or moderator to get this fixed!</p>    

<ul>{% for member in admins %}
<li><a href='{% url "profiles:profile" member.profile.slug %}'>Go To {{ member }}'s profile.</a>
</li>{% endfor %}</ul>    
    
</div>     
    
{% endblock %}



{% block footer %}
    <br><br><br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br>
    
    {% include 'footer.html'%}
    
{% endblock %}

profiles/templates/login.html
{% extends 'base.html' %}


{% block content %}
    
<br>

<div class='col-lg-12'>

<h2 style='text-align: center; color: #3366FF'>Log in here!</h2>



<form style='text-align: center' method='POST' action=''>{% csrf_token %}

{{ form.as_ul }}

<input class='btn btn-register' style='margin-left: 50px' type='submit'>


</form>

</div>    

 

  
    
    
{% endblock %}




{% block footer %}
    <br><br><br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br>
    
    {% include 'footer.html'%}
    
{% endblock %}

profiles/templates/profile.html
{% extends 'base.html'%}

{% block title %}
    
    <title>{{ object.user.username }}</title>
    
{% endblock %}


{% block jquery %}


$(function() {
   $( "#dialog" ).dialog({
     autoOpen: false,
     modal: true,
     width: 600,
     show: {
       effect: "blind",
       duration: 200
     },
     hide: {
       effect: "explode",
       duration: 200
     },
     

   });
   
   $( ".update" ).click(function() {

     $( "#dialog" ).dialog( "open" );
     console.log('the second dialog box was opened');
   });    
   
   
   
});

$(function(){
    $('#dialog-compose').dialog({
        autoOpen: false,
        modal:true,
        width:600,
        show: {
            effect: 'blind',
            duration:200
        },
        hide: {
            effect: 'explode',
            duration: 200
        },
    });
    $('.compose').click(function(){
        $('#dialog-compose').dialog('open');
        
    });
});




{% endblock %}


{% block content %}
    
 
    
<div class='col-sm-7'>
    <h1 style='margin-left:200px;'>{{ object.user.username }}</h1>

        <hr>
            {% if object.avatar %}
    <img src='{{MEDIA_URL}}{{object.avatar}}' class='img-responsive' style='margin-left:140px'/>
            {% elif request.user == object.user %}
    <p>It looks like you haven't set an avatar yet!</p>
            {% elif request.user != object.user %}
    <p>This person hasn't set an avatar yet!</p>
            {% endif %}
    <h3 style='margin-left:220px'>Info</h3>
    <hr>
            {% if object.description %}
    <p>{{ object.description }}</p>
            {% elif request.user == object.user %}
    <p>Tell us about yourself!</p>
            {% elif request.user != object.user %}
    <p>This person hasn't written a description.</p>
            {% endif %}
    <hr>
            {% if request.user != object.user %}    
    <a href='{% url "directmessages:compose" object.pk%}' class='btn btn-success' style='margin-left: 70px'>Send Private Message</a>
            {% else %}
    <div class='btn-group' role='group' aria-label='...'>
    <button class='btn btn-reply update'>Update Profile</button>
    <button class='btn btn-quote compose'>Compose Private Message</button>
    
    
        <a class='btn btn-report outbox' href='{% url "directmessages:outbox" object.slug%}'>View Outbox</a>
        <a class='btn btn-register' href='{% url "directmessages:inbox" object.slug %}'>View Inbox</a>

    </div>
    
    
    
            {% endif %}
</div>
    
<div class='col-sm-5'>
    <h1 style='text-align:center'>Posting Stats</h1>
    <table class='table'>
        <thead>
            <th></th>
            <th></th>


        </thead>
        <tbody>
            <tr><td>Postcount</td><td class='pull-right'>{{ object.get_num_posts }}</td></tr>
            <tr><td>Favorite Forum</td><td class='pull-right'>
                <a href='{{ object.get_favorite_forum.get_absolute_url }}'>
                    {{ object.get_favorite_forum}}</a></td></tr>
            <tr><td>Favorite Thread</td><td class='pull-right'>
            <a href='{{ object.get_favorite_thread.get_absolute_url }}'>
                {{ object.get_favorite_thread }}</a></td></tr>
        </tbody>
    </table>
    <hr>
    <h1 style='text-align:center'>Recent Posts</h1>
    <hr>

    <table class='table'>
        {% for post in object.get_last_five_posts %}
        <tr><td><a href='{{ post.get_absolute_url }}'>{{post.thread.title}}</a>
        
        </td><td class='pull-right'>{{ post.created }}</td></tr>
        {% endfor %}
        
        
        
    </table>
</div>

<div class='col-sm-12'><br><br><br><br><hr>
</div>

</div>


<div id="dialog" title="Edit Profile">
 
  <div>

        
        
        
      <form style='width: 800px'method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
      {{ form.as_p }}
    <input class='btn btn-reply' type='submit' value='Update' style='margin-left: 250px'/></form>


    
    


  </div>
</div> 

<div id='dialog-compose' title='Select a user'>
    <div class='table' style='overflow: scroll; height: 500px;'>
        <table class='table'>
            
            {% for profile in object.get_all_profiles %}
                {% if profile != request.user %}
            <tr><td style='text-align: center'>
            <a href='{% url "directmessages:compose" profile.pk %}' class='btn btn-compose'>{{ profile }}</a></td></tr>
                {% else %}
                {% endif %}
        {% endfor %}

        </table>    
    </div> 
</div>





{% endblock %}
    
<div class='container'>    
{% block footer %}

{% include 'footer.html'%}
{% endblock %}</div>

profiles/templates/profile_index.html
{% extends 'base.html' %}


{% block title %}
    
    <title>All Profiles</title>
    
{% endblock %}




{% block stylesheet %}
    
{% endblock %}


{% block content %}
  
<div class='row'>
    
    <h2 style='text-align: center'>Users</h2>
    
</div>
    <hr>
    <div class='row'>
    {% for object in object_list %}
        
        <div class='col-sm-4' style='text-align: center;'>
    <div class="thumbnail toggle" style='background-color: #33CC33; border-radius:11px;'>
        {% if object.avatar %}
      <img src='{{MEDIA_URL}}{{object.avatar}}' class='img-responsive'
           style='height: 100px; width:100px; margin-top:20px;'alt="...">
        {% else %}
        <img src="http://media.giphy.com/media/kHIJtQ981gP1C/200_s.gif"
             style='height: 100px; width:100px;margin-top:20px;'alt="...">
        {% endif %}
      <div class="caption">
        <h3 style='color: gold'>{{ object }}</h3>
        <p></p>
        <p><a href="{% url "profiles:profile" object.slug %}" class="btn btn-primary" role="button">View Profile</a></p>
      </div>
    </div>

            
        

        
    

</div>
        
        <!-- this will make a new row after 3 pics -->
        {% cycle '' '' '</div><br/><div class="row">'%}
{% endfor %}
    </div>
<br/>  
{% endblock %}

{% block footer %}
    
    {% include 'footer.html'%}
    
{% endblock %}
 
 
   
   
    
    

profiles/templates/register.html
{% extends 'base.html' %}


{% block content %}
    
<br>

<div class='col-lg-12'>

<h2 style='text-align: center; color: #3366FF'>New? Register Here!</h2>



<form style='text-align: center' method='POST' action=''>{% csrf_token %}

{{ form.as_ul }}

<input class='btn btn-register' name='register' style='margin-left: 50px' type='submit'>


</form>

</div>    

 

  
    
    
{% endblock %}



{% block footer %}
    <br><br><br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br>
    
    {% include 'footer.html'%}
    
{% endblock %}